# Generated by Django 3.2.6 on 2021-11-09 22:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=9, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('city', models.CharField(max_length=32, null=True)),
                ('postcode', models.CharField(max_length=6, null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_contract', models.DateField()),
                ('client', models.ManyToManyField(to='reservation.Client')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_leader', to='reservation.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_owner', to='reservation.client')),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=16)),
                ('full_name', models.CharField(max_length=128)),
                ('VAT_no', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=16)),
                ('post_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('hash', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('link', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('category', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='*', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_message', models.DateField(auto_now_add=True)),
                ('message_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.country')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('dest_from', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('dest_to', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('link', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('size', models.IntegerField(null=True)),
                ('rooms_no', models.IntegerField(null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.region')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('room_size', models.IntegerField(null=True)),
                ('terrace_size', models.IntegerField(null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.region'),
        ),
        migrations.CreateModel(
            name='ContractVilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('price_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.contract')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.counterparty')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.mealplan')),
                ('net_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_villa_currency', to='reservation.currency')),
                ('offer_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_villa_currency', to='reservation.currency')),
                ('villa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.villa')),
            ],
        ),
        migrations.CreateModel(
            name='ContractTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_category', models.CharField(max_length=32)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('price_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.contract')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.counterparty')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.mealplan')),
                ('net_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_train_currency', to='reservation.currency')),
                ('offer_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_train_currency', to='reservation.currency')),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.train')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('room_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.contract')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.counterparty')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.mealplan')),
                ('net_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_room_currency', to='reservation.currency')),
                ('offer_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_room_currency', to='reservation.currency')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.room')),
            ],
        ),
        migrations.CreateModel(
            name='ContractProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('price_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.contract')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.counterparty')),
                ('net_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_product_currency', to='reservation.currency')),
                ('offer_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_product_currency', to='reservation.currency')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.reference'),
        ),
    ]
