# Generated by Django 3.2.9 on 2022-01-15 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractticket',
            name='date_arrival',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractticket',
            name='date_departure',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
