# Generated by Django 3.2.9 on 2022-01-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220115_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractticket',
            name='extra_nores',
            field=models.CharField(max_length=12800, null=True),
        ),
    ]
