# Generated by Django 3.2.6 on 2021-11-22 20:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_hotel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('link', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('-', '-'), ('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], default='*', max_length=5),
        ),
        migrations.CreateModel(
            name='ContractTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('departure', models.DateField()),
                ('arrival', models.DateField()),
                ('price_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_class', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.airline')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.counterparty')),
                ('net_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_ticket_currency', to='reservation.currency')),
                ('offer_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_ticker_currency', to='reservation.currency')),
            ],
        ),
    ]
