# Generated by Django 3.1 on 2020-08-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20200810_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='link',
            field=models.CharField(default='www.google.com', max_length=128),
        ),
    ]
