# Generated by Django 3.2.6 on 2021-10-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_client_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continent',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='country',
            name='hash',
        ),
    ]
