# Generated by Django 3.2.9 on 2022-01-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_rename_extra_nores_contractticket_extra_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractticket',
            name='date_arrival',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contractticket',
            name='date_departure',
            field=models.DateTimeField(),
        ),
    ]
