# Generated by Django 3.2.6 on 2021-10-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20211007_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
    ]
