# Generated by Django 3.1 on 2020-08-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20200811_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.region'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.continent'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.country'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='link',
            field=models.CharField(default='', max_length=128),
        ),
    ]
