# Generated by Django 3.2.6 on 2021-10-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20211008_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractroom',
            name='room_category',
        ),
    ]
