# Generated by Django 3.2.6 on 2021-10-16 10:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_remove_contractroom_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractroom',
            name='room_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('link', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('size', models.IntegerField(null=True)),
                ('rooms_no', models.IntegerField(null=True)),
                ('pool', models.BooleanField(default=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.region')),
            ],
        ),
    ]
