# Generated by Django 3.1 on 2020-08-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20200811_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='hash',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
