# Generated by Django 3.2.9 on 2022-02-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20220207_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractticket',
            name='date_arrival',
        ),
        migrations.RemoveField(
            model_name='contractticket',
            name='date_departure',
        ),
        migrations.RemoveField(
            model_name='contractticket',
            name='ticket',
        ),
        migrations.AddField(
            model_name='contractticket',
            name='ticket_details',
            field=models.CharField(max_length=12800, null=True),
        ),
    ]
