# Generated by Django 3.1 on 2020-08-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_remove_currency_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='paid',
        ),
    ]
