# Generated by Django 3.2.9 on 2022-02-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20220207_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractticket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
