# Generated by Django 3.2.9 on 2022-02-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_contractticket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractticket',
            name='ticket_details',
            field=models.TextField(null=True),
        ),
    ]
