# Generated by Django 3.2.9 on 2022-02-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_contractticket_ticket_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cancellation_policy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_policy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contractticket',
            name='extra_notes',
            field=models.TextField(null=True),
        ),
    ]
