# Generated by Django 3.2.9 on 2022-02-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20220207_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date_of_sign',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_of_contract',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
