# Generated by Django 3.1 on 2020-08-16 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_auto_20200816_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.currency')),
                ('reservation', models.ForeignKey(on_delete=models.SET('Usuniety'), to='reservation.reservation')),
                ('room', models.ForeignKey(on_delete=models.SET('usunięty'), to='reservation.room')),
            ],
        ),
    ]
