# Generated by Django 3.2.9 on 2022-02-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_auto_20220207_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_of_sign',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_policy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
