# Generated by Django 3.1 on 2020-08-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_auto_20200816_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_service',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
