# Generated by Django 3.2.9 on 2022-02-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_contract_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinsurance',
            name='extra_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=14),
        ),
    ]
