# Generated by Django 3.1 on 2020-08-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_auto_20200816_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.reservation'),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.room'),
        ),
    ]
