# Generated by Django 3.2.9 on 2022-02-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_auto_20220211_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cancellation_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
