# Generated by Django 3.2.9 on 2022-02-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_auto_20220213_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractticket',
            name='date_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractticket',
            name='date_departure',
            field=models.DateField(blank=True, null=True),
        ),
    ]
