# Generated by Django 3.2.9 on 2022-02-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_auto_20220213_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=26)),
                ('currency_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.currency')),
            ],
        ),
    ]
