# Generated by Django 3.2.9 on 2022-02-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_bankaccounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccounts',
            new_name='BankAccount',
        ),
    ]
