# Generated by Django 3.1 on 2020-08-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_auto_20200817_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.reservation'),
        ),
    ]
