# Generated by Django 3.1 on 2020-08-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0020_auto_20200817_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
    ]
