# Generated by Django 3.2.9 on 2022-03-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0021_auto_20220228_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractfile',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contractfile',
            name='pdf',
            field=models.FileField(upload_to='pdfs'),
        ),
    ]
