# Generated by Django 3.1 on 2020-08-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0022_auto_20200817_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='price',
        ),
    ]
