# Generated by Django 3.2.9 on 2022-03-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0022_auto_20220311_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractfile',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
