# Generated by Django 3.1 on 2020-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0023_auto_20200818_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='room',
            name='price_service',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
