# Generated by Django 3.1 on 2020-08-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0024_auto_20200819_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_service',
            new_name='price',
        ),
    ]
