# Generated by Django 3.1 on 2020-08-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0025_auto_20200819_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
