# Generated by Django 3.1 on 2020-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0026_roomreservation_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_message', models.DateField(auto_now_add=True)),
                ('message_text', models.TextField()),
            ],
        ),
    ]
