# Generated by Django 3.2 on 2021-04-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0027_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='leader',
            field=models.BooleanField(default=False),
        ),
    ]
