# Generated by Django 3.2.6 on 2021-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0029_auto_20210817_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=16)),
                ('full_name', models.CharField(max_length=128)),
                ('VAT_no', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=16)),
                ('post_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
    ]
