# Generated by Django 3.2.6 on 2021-09-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0031_auto_20210825_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reservation', models.DateField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('room_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.counterparty')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.currency')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.hotel')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.roomcategory')),
            ],
        ),
    ]
