# Generated by Django 3.2.6 on 2021-09-26 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0032_reservation2_roomcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='counterparty',
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='price',
        ),
        migrations.AlterField(
            model_name='reservation2',
            name='room_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
