# Generated by Django 3.2.6 on 2021-09-26 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0032_reservation2_roomcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation2',
            name='room_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
