# Generated by Django 3.2.6 on 2021-09-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0033_auto_20210926_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation2',
        ),
    ]
