# Generated by Django 3.2.6 on 2021-09-26 20:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0033_alter_reservation2_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='reservation2',
            old_name='price',
            new_name='price_net',
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='currency',
        ),
        migrations.AddField(
            model_name='reservation2',
            name='net_currency',
            field=models.ForeignKey(default='All', on_delete=django.db.models.deletion.CASCADE, related_name='net_currency', to='reservation.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation2',
            name='offer_currency',
            field=models.ForeignKey(default='BLA', on_delete=django.db.models.deletion.CASCADE, related_name='offer_currency', to='reservation.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation2',
            name='price_offer',
            field=models.DecimalField(decimal_places=2, default='VLA', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation2',
            name='room_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='reservation2',
            name='meal_plan',
            field=models.ForeignKey(default='All inC', on_delete=django.db.models.deletion.CASCADE, to='reservation.mealplan'),
            preserve_default=False,
        ),
    ]
